name: pysurvival
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy=1.24.3
  - pandas=2.0.3
  - scipy=1.10.1
  - scikit-learn=1.3.0
  - matplotlib-base=3.7.2
  - seaborn=0.13.2
  - statsmodels=0.14.0
  - pip=24.0
  - pip:
    - streamlit==1.38.0
    - pysurvival==0.1.2
    - lifelines==0.27.8
    - survivaleval==0.3.0

